---
    - block:

        - name: Write decrypted private key to temporary file
          copy:
            content: "{{ github_backend_priv_key }}"
            dest: /tmp/github_key
            mode: '0600'

        - name: Clone private repo
          git:
            repo: 'git@github.com:alexsfa/myretirement_api.git'
            dest: /home/ubuntu/myretirement_api
            key_file: /tmp/github_key
            version: main
            force: yes
            accept_hostkey: yes

      always:
        - name: Remove temporary private key
          file:
            path: /tmp/github_key
            state: absent

    - name: Generate .env file from template
      template:
        src: .templates/backend/env.j2
        dest: "{{ dev_environment | ternary('/home/ubuntu/myretirement_api/.env.dev', '/home/ubuntu/myretirement_api/.env.prod') }}"

    - name: Add DJANGO_ALLOWED_HOSTS field to the .env file
      ansible.builtin.lineinfile:
        path: "{{ dev_environment | ternary('/home/ubuntu/myretirement_api/.env.dev', '/home/ubuntu/myretirement_api/.env.prod') }}" 
        line: "{{ dev_environment | ternary(
                    'DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1'
                    'DJANGO_ALLOWED_HOSTS=' ~ hostvars['localhost'][docker_host_ip]
                  ) }}"
        create: yes
        state: present

    - name: Start backend services
      ansible.builtin.shell: >
        docker compose --profile "{{ dev_environment | ternary('dev', 'prod') }}"
        --env-file ".env.{{ dev_environment | ternary('dev', 'prod') }}" up -d
      args:
        chdir: /home/ubuntu/myretirement_api

    

