---
  - name: Pull backend from remote repository
    block:

      - name: Write decrypted private key to temporary file
        copy:
          content: "{{ github_backend_priv_key }}"
          dest: /tmp/github_key
          mode: '0600'

      - name: Clone private repo
        git:
          repo: 'git@github.com:alexsfa/myretirement_api.git'
          dest: /home/ubuntu/myretirement_api
          key_file: /tmp/github_key
          version: main
          force: yes
          accept_hostkey: yes

    always:
      - name: Remove temporary private key
        file:
          path: /tmp/github_key
          state: absent
  
  - name: Pull frontend from remote repository
    block:

      - name: Write decrypted private key to temporary file
        copy:
          content: "{{ github_frontend_priv_key }}"
          dest: /tmp/github_key
          mode: '0600'

      - name: Clone private repo
        git:
          repo: 'git@github.com:alexsfa/myretirement_gui.git'
          dest: /home/ubuntu/myretirement
          key_file: /tmp/github_key
          version: main
          force: yes
          accept_hostkey: yes

    always:
      - name: Remove temporary private key
        file:
          path: /tmp/github_key
          state: absent
          
  - name: Generate .env file from template
    template:
      src: templates/env.j2
      dest: "{{ dev_environment | ternary('/home/ubuntu/myretirement_api/.env.dev', '/home/ubuntu/myretirement_api/.env.prod') }}"
      
  - name: Add DJANGO_ALLOWED_HOSTS field to the .env file
    ansible.builtin.blockinfile:
      path: "{{ dev_environment | ternary('/home/ubuntu/myretirement_api/.env.dev', '/home/ubuntu/myretirement_api/.env.prod') }}" 
      block: |
        CORS_ALLOWED_ORIGINS=http://{{ hostvars['localhost']['docker_host_ip'] }}:5173,http://localhost:5173
        {{ dev_environment | ternary('DJANGO_ALLOWED_HOSTS='~ hostvars['localhost']['docker_host_ip'] ~',localhost,127.0.0.1,app-dev','DJANGO_ALLOWED_HOSTS=myretirement.click, 127.0.0.1') }}
      create: yes
      state: present
      marker: ""
          
  - name: Add additional fields for Vite Dev Server (only for dev)
    ansible.builtin.blockinfile:
      path: "/home/ubuntu/myretirement_api/.env.dev"
      block: |
        VITE_DEV_HOST={{ hostvars['localhost']['docker_host_ip'] }}
        VITE_API_TARGET=http://app-dev:8000
      create: yes
      marker: ""
    when: dev_environment | bool
    
  - name: Deploy the app with Docker compose
    ansible.builtin.shell: >
      docker compose --profile "{{ dev_environment | ternary('dev', 'prod') }}"
      --env-file ".env.{{ dev_environment | ternary('dev', 'prod') }}" up -d
    args:
      chdir: /home/ubuntu/myretirement_api
    
  
          
  
