---
    - block:

        - name: Write decrypted private key to temporary file
          copy:
            content: "{{ github_frontend_priv_key }}"
            dest: /tmp/github_key
            mode: '0600'

        - name: Clone private repo
          git:
            repo: 'git@github.com:alexsfa/myretirement_gui.git'
            dest: /home/ubuntu/myretirement
            key_file: /tmp/github_key
            version: main
            force: yes
            accept_hostkey: yes

      always:
        - name: Remove temporary private key
          file:
            path: /tmp/github_key
            state: absent

    - name: Create .env and enter the VITE_API_URL
      ansible.builtin.lineinfile:
        path: "{{ dev_environment | ternary('/home/ubuntu/myretirement/.env.dev',
                                            '/home/ubuntu/myretirement/.env.prod') }}"
        line: "{{ dev_environment | ternary('VITE_API_URL='~ hostvars['localhost']['docker_host_ip'],
                                            'VITE_API_URL=/api/') }}"
        create: yes
        state: present


    - name: Create VITE_DEV_HOST (only for dev)
      ansible.builtin.lineinfile:
        path: "/home/ubuntu/myretirement/.env.dev"
        line: "VITE_DEV_HOST={{ hostvars['localhost']['docker_host_ip'] }}"
        create: yes
        state: present
      when: dev_environment | bool

    - name: Start frontend services
      ansible.builtin.shell: >
        docker compose --profile "{{ dev_environment | ternary('dev', 'prod') }}"
        --env-file ".env.{{ dev_environment | ternary('dev', 'prod') }}" up -d
      args:
        chdir: /home/ubuntu/myretirement

  
     

