---
    - block:

        - name: Write decrypted private key to temporary file
          copy:
            content: "{{ github_backend_priv_key }}"
            dest: /tmp/github_key
            mode: '0600'

        - name: Clone private repo
          git:
            repo: 'git@github.com:alexsfa/myretirement_api.git'
            dest: /home/ubuntu/myretirement_api
            key_file: /tmp/github_key
            version: main
            force: yes
            accept_hostkey: yes

      always:
        - name: Remove temporary private key
          file:
            path: /tmp/github_key
            state: absent

    - name: Generate .env file from template
      template:
        src: env.j2
        dest: /home/ubuntu/myretirement_api/.env.prod

    - name: Add DJANGO_ALLOWED_HOSTS field to the .env file
      ansible.builtin.lineinfile:
        path: /home/ubuntu/myretirement_api/.env.prod
        line: "DJANGO_ALLOWED_HOSTS={{ hostvars['localhost']['docker_host_ip'] }}"
        create: yes
        state: present

    - name: Start backend services
      ansible.builtin.shell: docker compose --profile prod --env-file .env.prod up -d
      args: 
        chdir: /home/ubuntu/myretirement_api
        
    

