---
- name: Create SGs for each component's host
  hosts: localhost
  tasks:
  
  - name: Create the Vue host's instance and confirm that it's reachable
    block:
    
      - name: Check for existing Vue host
        amazon.aws.ec2_instance_info:
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          filters:
            "tag:Name": vue_host
            "instance-state-name": running
        register: vue_host_running
    
      - name: Launch the Vue host
        amazon.aws.ec2_instance:
          name: "vue_host"
          image_id: ami-020cba7c55df1f615
          key_name: vue-host-key
          instance_type: t2.micro
          count: 1
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          vpc_subnet_id: 
          network_interfaces:
            - device_index: 0
              subnet_id: subnet-045e46c91af1579fc
              groups:
               - "{{ vue_sg_id }}"
              assign_public_ip: true
          wait: yes
          tags:
            Environment: "{{ 'dev' if dev_environment | bool else 'prod' }}"
        when: vue_host_running.instances | length == 0
        register: vue_host
        
      - name: Set host IP fact
        set_fact:
          vue_host_ip: >-
            {{ vue_host.instances[0].public_ip_address
              if vue_host.changed
              else vue_host_running.instances[0].public_ip_address }}
        
      - name: Add the Vue host on dynamic inventory
        add_host:
          name: "{{ vue_host_ip }}"
          groups: 
            - vue_servers
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/vue-host-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      - name: Wait for SSH connection with Vue host
        ansible.builtin.wait_for:
          host: "{{ vue_host_ip }}"
          port: 22
          timeout: 300
          state: started
        delegate_to: localhost
        
  - name: Create the Django host's instance and confirm that it's reachable
    block:
    
      - name: Check for existing Django host
        amazon.aws.ec2_instance_info:
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          filters:
            "tag:Name": django_host
            "instance-state-name": running
        register: django_host_running
    
      - name: Launch the Django host
        amazon.aws.ec2_instance:
          name: "django_host"
          image_id: ami-020cba7c55df1f615
          key_name: django-host-key
          instance_type: t2.micro
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          count: 1
          network_interfaces:
            - device_index: 0
              subnet_id: subnet-045e46c91af1579fc
              groups:
                - "{{ django_sg_id }}"
              assign_public_ip: true
          wait: yes
          tags:
            Environment: "{{ 'dev' if dev_environment | bool else 'prod' }}"
        when: django_host_running.instances | length == 0
        register: django_host
        
      - name: Set host IP fact
        set_fact:
          django_host_ip: >-
            {{ django_host.instances[0].public_ip_address
              if django_host.changed
              else django_host_running.instances[0].public_ip_address }}
      
      - name: Add the Django host on dynamic inventory
        add_host:
          name: "{{ django_host_ip }}"
          groups: 
            - django_servers
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/django-host-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      - name: Wait for SSH connection with Django host
        ansible.builtin.wait_for:
          host: "{{ django_host_ip }}"
          port: 22
          timeout: 300
          state: started
        delegate_to: localhost
        
  - name: Create the MySql host's instance and confirm that it's reachable
    block:
    
      - name: Check for existing MySql host
        amazon.aws.ec2_instance_info:
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          filters:
            "tag:Name": mysql_host
            "instance-state-name": running
        register: mysql_host_running
    
      - name: Launch the MySql host
        amazon.aws.ec2_instance:
          name: "mysql_host"
          image_id: ami-020cba7c55df1f615
          key_name: mysql-host-key
          instance_type: t2.micro
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          count: 1
          network_interfaces:
            - device_index: 0
              subnet_id: subnet-045e46c91af1579fc
              groups:
                - "{{ mysql_sg_id }}"
              assign_public_ip: true
          wait: yes
          tags:
            Environment: "{{ 'dev' if dev_environment | bool else 'prod' }}"
        when: mysql_host_running.instances | length == 0  
        register: mysql_host
        
      - name: Attach existing EBS to MySQL host
        amazon.aws.ec2_vol:
          id: "{{ mysql_data_ebs }}"
          instance: "{{ mysql_host.instances[0].instance_id }}"
          device_name: /dev/sdf 
          state: present
        when: mysql_host_running.instances | length == 0
        
      - name: Set host IP fact
        set_fact:
          mysql_host_ip: >-
            {{ mysql_host.instances[0].public_ip_address
              if mysql_host.changed
              else mysql_host_running.instances[0].public_ip_address }}
        
      - name: Add the MySQL host on dynamic inventory
        add_host:
          name: "{{ mysql_host_ip }}"
          groups: 
            - mysql_servers
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/mysql-host-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      - name: Wait for SSH connection with MySQL host
        ansible.builtin.wait_for:
          host: "{{ mysql_host_ip }}"
          port: 22
          timeout: 300
          state: started
        delegate_to: localhost
    
  - name: Create the Mailhog host's instance and confirm that it's reachable
    block:
    
      - name: Check for existing Mailhog host
        amazon.aws.ec2_instance_info:
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          filters:
            "tag:Name": mailhog_host
            "instance-state-name": running
        register: mailhog_host_running
    
      - name: Launch the Mailhog host
        amazon.aws.ec2_instance:
          name: "mailhog_host"
          image_id: ami-020cba7c55df1f615
          key_name: mailhog-host-key
          instance_type: t2.micro
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          count: 1
          network_interfaces:
            - device_index: 0
              subnet_id: subnet-045e46c91af1579fc
              groups:
                - "{{ mailhog_sg_id }}"
              assign_public_ip: true
          wait: yes
          tags:
            Environment: "{{ 'dev' if dev_environment | bool else 'prod' }}"
        when: mailhog_host_running.instances | length == 0
        register: mailhog_host
        
      - name: Set host IP fact
        set_fact:
          mailhog_host_ip: >-
            {{ mailhog_host.instances[0].public_ip_address
              if mailhog_host.changed
              else mailhog_host_running.instances[0].public_ip_address }}
          
      - name: Add the Mailhog host on dynamic inventory
        add_host:
          name: "{{ mailhog_host_ip }}"
          groups: 
            - mailhog_servers
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/mailhog-host-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      - name: Wait for SSH connection with Mailhog host
        ansible.builtin.wait_for:
          host: "{{ mailhog_host_ip }}"
          port: 22
          timeout: 300
          state: started
        delegate_to: localhost
          
  - name: Create the Nginx host's instance and confirm that it's reachable
    block:
    
      - name: Check for existing Nginx host
        amazon.aws.ec2_instance_info:
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          filters:
            "tag:Name": nginx_host
            "instance-state-name": running
        register: nginx_host_running
    
      - name: Launch the Nginx host
        amazon.aws.ec2_instance:
          name: "nginx_host"
          image_id: ami-020cba7c55df1f615
          key_name: nginx-host-key
          instance_type: t2.micro
          region: "{{ lookup('env', 'AWS_DEFAULT_REGION') }}"
          count: 1
          network_interfaces:
            - device_index: 0
              subnet_id: subnet-045e46c91af1579fc
              groups:
                - "{{ nginx_sg_id }}"
              assign_public_ip: true
          wait: yes
          tags:
            Environment: "prod"
        when: nginx_host_running.instances | length == 0
        register: nginx_host
        
      - name: Set host IP fact
        set_fact:
          nginx_host_ip: >-
            {{ nginx_host.instances[0].public_ip_address
              if nginx_host.changed
              else nginx_host_running.instances[0].public_ip_address }}
          
      - name: Add the Nginx host on dynamic inventory
        add_host:
          name: "{{ nginx_host_ip }}"
          groups: 
            - nginx_servers
          ansible_user: ubuntu
          ansible_ssh_private_key_file: "{{ lookup('env','HOME') }}/.ssh/nginx-host-key.pem"
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"

      - name: Wait for SSH connection with Nginx host
        ansible.builtin.wait_for:
          host: "{{ nginx_host_ip }}"
          port: 22
          timeout: 300
          state: started
        delegate_to: localhost
          
    when: not dev_environment      