github_frontend_priv_key: |  
  -----BEGIN RSA PRIVATE KEY-----
  MIIEpAIBAAKCAQEAp2VFhBy1XCoH7Nz+5zU/EnXEKaV1J7G7R3R8p9OQL5KbrJ/I
  N6sGvczPF4hDk2dTNsggdZxeVC8sJQaFDnCR9GvIDiIMQe6hPq7eUxG8mckfNyEa
  yKhTVTxUO/6eFlCU59yoVbwYWUQjViMKivoq0uwUomzBlxzoqwfzgkMgqRDfvsJg
  XgkEsl0px8fAsUUaMo0UBaPojeV/lF/wzs8aFQ8G6VGBPm8hKtCS3GTtI3Pa/zTt
  MdgTpbWBOaN9ua1UM5UcnVt/ZqeycT5mbtk2yT0SsnMXrf60Gf7toLvX102HaF2c
  +LuuiHtHIAKZZlTWIpjoXSpeQN4b+nZQi6wIdwIDAQABAoIBACZR0gyQr9mly4On
  AXk3ILWenOW1uTB5iLguS9z1WuPxCU8GksRfk97+FAg8is+jDxMS1A9oWNWnqNDf
  AbWRAnBz/etyUuEC+gmJ6V4VyNlhh5JMsz9s/QqdkWDchB7ymmvLgQODWAWTSg2N
  Xvv6kbQQFBcsk1J+7So92zoeGMtqsRusrFr3yeOrAj5MCaqWFZgChPOyi8EV5bDB
  3HS53dJEvqgp8sGHeF8O8G16RXCHRcEhDVQMYzQ4WzgGykD4VWocEapw1PQy/0wx
  1TjM5CKYwjDJr3BzAURUp62aL4CqLPuYFycs24jRt+57Q9E/I6w0IkHjyMJG3pkC
  M8omIgkCgYEA11OI5E4zJ70U2MsU/lEEY35bYmIhnwgdexOcMZpG8y2Zk7f3SfSI
  xXi0+H4OppfpwK3QPEtzhl6IA3ZrgQ+OZuSDChBvXN7L9cVhIh0BmTCzU3ml7+Vj
  coFIbCzgasX9lGVbw6kN+4HriymnTOPBdRUmZ9VkIT6vWo2T/RZDwc8CgYEAxwP3
  cEbhfpq+W1tP+AoizDhB9NUUUfm4CFkmbGA8PiSL0DnvB+t9iW0hbAh6HGr8khUB
  /G5nothJlFB9bGTdpIy487Lsb2/TJToFU1vzXMvTQMUGhSViKDD5iD+EJI62Fz3+
  4CQJoIixw4SoM059Nu7jpydn3UMrAx+FJwbnQNkCgYEAjDwROW9cjZLtUsvgXkjx
  bMLMTWTPtL0aRh/dZ8isUI/wJ252lSm3MbSNWBDxBbqGOEB7D+mr0WUbe/XRyfoR
  qh1E4ncVsAxCFUx5GDh/4/79q23cjkJ85AQi4KDRf3h20AC7JNCjFJvmhXmZRdBH
  HDOsEY++aJBkr7rpGLk5Y60CgYAZ15wDylBxnipltn+116sZFZ0K67hNxL1u6BSj
  MgPgleJJ0ZwGTT/p3m/elWM12XaeiXfOjY+Lh8ZWKfV/Y8GcImHJ00v8VGr4hIY4
  gtIhFJ6D5JGqLGaIjYN5e7XvAVEHx5cXB9bwL4/VsZ4du21q+q45AFbuVlB5gVhK
  7wyMUQKBgQC785xXeXppZIdQAkSrRAkHUyGe7giF6S3U0pN/fxjFvaBvRcCYYykT
  JP4wBUi/dc+/QJkpveXgh5GfCipQYBzZFI6K4xG2yV5eE4C8cRL1EBAuhlb3MaX8
  cy2m0FTCF67sjfRd4HaSigR84MdqNiVUc+ucGDYh00rg/ShiBoOodg==
  -----END RSA PRIVATE KEY-----
  
