---
- name: Install and configure all the prerequirements on the MySQL host
  hosts: mysql_servers
  become: yes
  vars_files:
    - ../vars/db_credentials.yml
  tasks:
  
    - name: Update apt
      apt:
        update_cache: yes
        
    - name: Install MySQL and verify that is running
      block:
          
        - name: Install MySQL
          package:
            name: "{{ item }}"
            state: present
          loop:
            - mysql-server
            - python3-pymysql  # required for Ansible MySQL modules
        
        - name: Ensure MySQL service is running
          service:
            name: mysql
            state: started
            enabled: yes
          

      
    - name: Create admin user for Ansible
      mysql_user:
        name: "{{ dev_db_credentials.DB_ADMIN_NAME }}"
        password: "{{ dev_db_credentials.DB_ADMIN_PASS }}"
        priv: "*.*:ALL,GRANT"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock
            
    - name: Create application db
      mysql_db:
        name: "{{ item }}"
        state: present
        login_user: "{{ dev_db_credentials.DB_ADMIN_NAME }}"
        login_password: "{{ dev_db_credentials.DB_ADMIN_PASS }}"
      loop:
        - "{{ dev_db_credentials.DB_NAME }}"
        - "test_{{ dev_db_credentials.DB_NAME }}"
            
    - name: Create application user
      mysql_user:
        name: "{{ dev_db_credentials.DB_USER }}"
        host: "{{ hostvars['localhost'].django_host_private_ip }}"
        password: "{{ dev_db_credentials.DB_PASS }}"
        priv: "{{ dev_db_credentials.DB_NAME }}.*:ALL, test_{{ dev_db_credentials.DB_NAME }}.*:ALL"
        state: present
        login_user: "{{ dev_db_credentials.DB_ADMIN_NAME }}"
        login_password: "{{ dev_db_credentials.DB_ADMIN_PASS }}"
        
    - name: Configure MySQL to bind to server IP
      lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address'
        line: "bind-address = 0.0.0.0"
        backup: yes
      notify: Restart MySQL
      
  handlers:
    - name: Restart MySQL
      service:
        name: mysql
        state: restarted

        
        
      

        
    
  
    