---
- name: Configure Django host
  hosts: django_servers
  gather_facts: yes
  become: yes
  tasks:
  
    - name: Update apt
      apt:
        update_cache: yes
        
    - name: Install required packages
      apt:
        name:
          - build-essential # gcc, make and others
          - libffi-dev # requied for some Python packages
          - linux-headers-{{ ansible_kernel }} # for kernel modules
          - libmariadb-dev # C dependency for some Python packages
          - libmariadb-dev-compat
          - python3-dev  # provides python headers
          - python3-venv
          - pkg-config # for mysqlclient
        state: present
        
    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /py
      args:
        creates: /py/bin/activate
        
    - name: Upgrade pip in the virtual environment
      ansible.builtin.command:
        cmd: /py/bin/python -m pip install --upgrade pip
    
    - name: Install required packages on the venv
      block:
      
        - name: Copy requirements.txt to remote host
          ansible.builtin.copy:
            src: ../vars/requirements/backend_requirements.txt   
            dest: /tmp/backend_requirements.txt  

        - name: Install Python packages from requirements.txt
          ansible.builtin.pip:
            requirements: /tmp/backend_requirements.txt
            virtualenv: /py            
            virtualenv_python: python3  
        
    - name: Install required packages for development on the venv
      block:
      
        - name: Copy requirements.dev.txt to remote host
          ansible.builtin.copy:
            src: ../vars/requirements/backend_requirements.dev.txt   
            dest: /tmp/backend_requirements.dev.txt 
        
        - name: Install Python packages from requirements.dev.txt
          ansible.builtin.pip:
            requirements: /tmp/backend_requirements.dev.txt
            virtualenv: /py            
            virtualenv_python: python3
              
      when: dev_environment | bool
      
    - name: Create Django system user
      ansible.builtin.user:
        name: django-user
        shell: /bin/bash
        create_home: no
        password: "*"


  