---
- name: Configure Django host
  hosts: django_servers
  gather_facts: yes
  become: yes
  tasks:
  
    - name: Update apt
      apt:
        update_cache: yes
        
    - name: Install required packages
      apt:
        name:
          - build-essential # gcc, make and others
          - libffi-dev # requied for some Python packages
          - linux-headers-{{ ansible_kernel }} # for kernel modules
          - libmariadb-dev # C dependency for some Python packages
          - libmariadb-dev-compat
          - python3-dev  # provides python headers
          - python3-venv
          - pkg-config # for mysqlclient
        state: present
        
    - name: Install MySQL client on Django host
      apt:
        name: mysql-client-core-8.0
        state: present
        update_cache: yes
        
    - name: Create Python virtual environment
      ansible.builtin.command:
        cmd: python3 -m venv /py
      args:
        creates: /py/bin/activate
        
    - name: Upgrade pip in the virtual environment
      ansible.builtin.command:
        cmd: /py/bin/python -m pip install --upgrade pip
      
    - name: Create Django system user
      ansible.builtin.user:
        name: django-user
        shell: /bin/bash
        create_home: no
        password: "*"


  